services:
  app:
    image: ${DOCKERHUB_USERNAME:-kage1414}/timeforge:latest
    environment:
      DATABASE_PATH: /data/db.sqlite
      PORT: "4000"
    ports:
      - "3000:4000"
    volumes:
      - dbdata:/data

volumes:
  dbdata:
