FROM node:22-alpine
RUN apk add --no-cache python3 make g++
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
ENV DATABASE_PATH=/data/db.sqlite
EXPOSE 4000
CMD ["sh", "-c", "yarn install && yarn dev"]
